# Site settings
title: Project Gonzo
email: jan@telenordigital.com
description: > # this means to ignore newlines until "baseurl:"
  With Gonzo we are building a small wireless always-on camera, connected
  over 2G, and with a month battery life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ee.telenor.io" # the base hostname & protocol for your site
twitter_username: janjongboom
github_username:  comoyo

# Build settings
markdown: kramdown
