# Site settings
title: Exploratory Engineering
description: > # this means to ignore newlines until "baseurl:"
  Exploratory Engineering is a concept where we run targeted 3 month projects
  exploring some high-risk / high-potential-return area, within Telenor Digital.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ee.telenor.io" # the base hostname & protocol for your site
github_username:  comoyo
website: "http://telenordigital.com/"
websiteTitle: Telenor Digital

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from